# Generated by Django 5.0.4 on 2025-08-12 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('modelo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_servico', models.DateField()),
                ('descricao', models.TextField()),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficina.motorista')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.oficina')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.veiculo')),
            ],
        ),
    ]
